# Generated by Django 5.1.7 on 2025-03-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diner',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
