# Generated by Django 5.1.7 on 2025-03-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_diner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='diner',
            name='hashed_password',
            field=models.CharField(default='some_hash', max_length=128),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='someone@example.com', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='hashed_password',
            field=models.CharField(default='some_hash', max_length=128),
        ),
        migrations.AlterField(
            model_name='diner',
            name='email',
            field=models.EmailField(default='someone@example.com', max_length=200),
        ),
    ]
