# Generated by Django 5.1.7 on 2025-06-06 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_feedback_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
